Krypton-Suite/Extended-Toolkit

Source/Krypton Toolkit/Examples/MessageBox/Form1.Designer.cs
Source/Krypton Toolkit/Examples/MessageBox/Form1.cs
Source/Krypton Toolkit/Examples/MessageBox/Form1.resx
Source/Krypton Toolkit/Examples/MessageBox/MessageBox.csproj
Source/Krypton Toolkit/Examples/MessageBox/Program.cs
Source/Krypton Toolkit/Krypton Toolkit Suite Extended.sln
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Classes/KryptonMessageBoxExtended.cs

- More work on #63 - Documentation
- Messageboxes can now have a custom icon - must be 32 x 32
- Begun work on a 'showcase' app to show messagebox features

* More on #63

---

Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Classes/TreeGridNodeCollection.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Classes/TreeGridNodeParentBuilder.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Components/KryptonTreeGridView.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Components/TreeGridCell.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Components/TreeGridNode.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Events/TreeGridEvents.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Tree.Grid.View/Krypton.Toolkit.Suite.Extended.Tree.Grid.View.licenseheader

* Implement #96

---

Source/Krypton Toolkit/Examples/DataGridView/ListExample.Designer.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridViewExt/Implementation/MasterDetailGridView.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridViewExt/Implementation/MasterDetailGridViewBase.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridViewExt/MasterMultiDetailView.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridViewExt/Readme.md
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridViewExt/SimpleFilteredList.cs

- If there are no Details Rows exist, then the Details view will not be shown. (And not `AllowUserToAddRows`)
- Have to display the Row Icon otherwise performance on having to perform a Select ands filter for each row seriously hits performance and redraw on resizing
- #122

- If there are no Details Rows exist, then the Details view will not be shown. (And not `AllowUserToAddRows`)

---

Documents/Examples/Examples.md
README.md

- Test to see if the Documentation links can be coded int the readme.md
#19

- Test to see if the Documentation links can be coded int the readme.md

---

Source/Krypton Toolkit/Krypton Toolkit Suite Extended.sln
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Effects/Classes/Fading/FadeController.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Effects/Components/Fading/FadeManager.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Effects/Krypton.Toolkit.Suite.Extended.Effects.csproj

* Fade effects

---

Source/Krypton Toolkit/Examples/Notifications/Form1.Designer.cs
Source/Krypton Toolkit/Examples/Notifications/Form1.cs
Source/Krypton Toolkit/Examples/Notifications/Form1.resx
Source/Krypton Toolkit/Examples/Notifications/Notifications.csproj
Source/Krypton Toolkit/Examples/Notifications/Program.cs
Source/Krypton Toolkit/Krypton Toolkit Suite Extended.sln
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Notifications/Components/KryptonToastNotificationManager.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Notifications/UX/Toast/Version 1/KryptonToastNotificationVersion1.cs

- Bug bashing
- Start on notification demo

Version next notifications

---

Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/ExtColumns/Formatting/ColourHelper.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/ExtColumns/KryptonDataGridViewRatingColumn.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/ExtColumns/KryptonDataGridViewTextAndImageColumn.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/Implementation/MasterDetailGridViewBase.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/Implementation/Portable.System.ValueTuple.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/Krypton.Toolkit.Suite.Extended.DataGridView 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/MasterMultiDetailView.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/MasterSingleDetailView.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/Readme.md
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/SimpleFilteredList.cs

- Reduced to only support Tuple'T2
- Remove other frameworks that Krypton does not support
- Remove public API
- Apply "Preview" coding style(s)
Fixes #217

- Reduced to only support Tuple'T2

---

Source/Krypton Toolkit/Examples/DataGridView/ListExample.Designer.cs
Source/Krypton Toolkit/Examples/DataGridView/ListExample.resx
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/ExtColumns/Formatting/KryptonByteViewer.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/ExtColumns/KryptonDataGridViewBinaryCell.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/ExtColumns/KryptonDataGridViewBinaryColumn.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/Krypton.Toolkit.Suite.Extended.DataGridView 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/MasterMultiDetailView.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/MasterSingleDetailView.cs

- Make sure it can be used in the designer
Implements #227

- Add BinaryView Grid Column Type

---

Source/Krypton Toolkit/Examples/MessageBox/Form1.Designer.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Drawing.Utilities/Controls/Components/ColourHexadecimalTextBox.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Drawing.Utilities/UX/KryptonColourPickerDialog.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Classes/InternalKryptonMessageBoxExtended.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Classes/PlatformInvoke.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Components/KryptonMessageBoxExtendedManager.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Designer/KryptonMessageBoxConfiguratorActionList.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Designer/KryptonMessageBoxConfiguratorDesigner.cs
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Messagebox/Events/ShowMessageBoxEventArgs.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Developer.Utilities/Classes/General/ApplicationUtilities.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Developer.Utilities/Classes/General/KryptonMessageBoxExtended.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Developer.Utilities/Classes/General/MethodHelpers.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Developer.Utilities/Classes/General/PlatformInvoke.cs
Source/Krypton Toolkit/Shared/Krypton.Toolkit.Suite.Extended.Developer.Utilities/Globals/GlobalDeclarations.cs

- Fix fallout from rename
- Update usage of Globals
- Make sure Message Entry in demo has scrollbars
Resolves #231

- Rename Manager

---

Source/Krypton Toolkit/Krypton Toolkit Suite Extended 2019 - Dev.sln
Source/Krypton Toolkit/Krypton Toolkit Suite Extended 2019 - Nightly.sln
Source/Krypton Toolkit/Krypton Toolkit Suite Extended 2019 - Nuget.sln
Source/Krypton Toolkit/Main/Directory.Build.props
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Buttons/Krypton.Toolkit.Suite.Extended.Buttons 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Calendar/Krypton.Toolkit.Suite.Extended.Calendar 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.CheckSum.Tools/Krypton.Toolkit.Suite.Extended.CheckSum.Tools 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Circular.ProgressBar/Krypton.Toolkit.Suite.Extended.Circular.ProgressBar 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.ComboBox/Krypton.Toolkit.Suite.Extended.ComboBox 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Compression/Krypton.Toolkit.Suite.Extended.Compression.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Controls/Krypton.Toolkit.Suite.Extended.Controls 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.Data.Visualisation/Krypton.Toolkit.Suite.Extended.Data.Visualisation 2019.csproj
Source/Krypton Toolkit/Main/Krypton.Toolkit.Suite.Extended.DataGridView/Krypton.Toolkit.Suite.Extended.DataGridView 2019.csproj
Source/Krypton Toolkit/Shared/Directory.Build.props
Source/Krypton Toolkit/Third Party/Directory.Build.props

- Need help to verify location

* Attempt to import toolkit

---

Documents/Help/Changelog.md

* Build 2202

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.CheckSum.Tools/Properties/Settings.Designer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Outlook.Grid/Resources/Language/Strings.es-ES.resx
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Settings/Settings/Globals/GlobalBooleanSettings.Designer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Settings/Settings/Globals/GlobalEnumerationSettings.Designer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Settings/Settings/Globals/GlobalStringSettings.Designer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Settings/Settings/Theming/GlobalThemeSettings.Designer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Theme.Switcher/Properties/Settings.Designer.cs

* Implement #315

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Forms/ButtonSpec/ButtonSpecFormWindowClose.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Forms/ButtonSpec/ButtonSpecFormWindowMax.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Forms/Controls Visuals/VirtualForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Forms/Controls Visuals/VirtualKryptonFormExtended.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Shared/General/PlatformInvoke.cs

* Implemented `CloseBox` in `KryptonManagerExtended` to fall in line with the standard toolkit

* `CloseBox` in `KryptonManagerExtended`

---

.gitignore
Source/Krypton Toolkit/Examples/AdvancedDataGridView.cs
Source/Krypton Toolkit/Examples/Examples.csproj
Source/Krypton Toolkit/Examples/MainWindow.Designer.cs
Source/Krypton Toolkit/Examples/MainWindow.cs
Source/Krypton Toolkit/Examples/MemoryBoxExample.Designer.cs
Source/Krypton Toolkit/Examples/MemoryBoxExample.cs
Source/Krypton Toolkit/Examples/MemoryBoxExample.resx
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Common/UX/CommonExtendedKryptonForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Error.Reporting/Krypton.Toolkit.Suite.Extended.Error.Reporting 2022.csproj
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Memory.Box/UX/KryptonMemoryBox.Designer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Memory.Box/UX/KryptonMemoryBox.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Networking/Krypton.Toolkit.Suite.Extended.Networking 2022.csproj
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Notifications/Classes/Alternative/Alert.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Notifications/UX/Alternative/KryptonAlertWindow.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Toast/Enumerations/IconType.cs

* Fixes regarding to recent changes to enums

* Fixes regarding to recent changes

---

Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Outlook.Grid/Classes/Helpers/ColourHelper.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Toggle.Switch/Classes/Renderer/Types/Vanilla/ToggleSwitchAndroidRenderer.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.VirtualTreeColumnView/Control/InternalTreeColumnView.cs

* Add more `nullables`

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Buttons/Controls Toolkit/Dialog Buttons/KryptonCancelDialogButton.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Buttons/Controls Toolkit/Dialog Buttons/KryptonNODialogButton.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Buttons/Controls Toolkit/Dialog Buttons/KryptonOKDialogButton.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Buttons/Controls Toolkit/Dialog Buttons/KryptonYesDialogButton.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Buttons/Controls Toolkit/General/KryptonDialogButtonExtended.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Buttons/Controls Toolkit/Internal/InternalKryptonButton.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.CheckSum.Tools/Controls Visuals/KryptonComputeFileCheckSum.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.CheckSum.Tools/Controls Visuals/KryptonVerifyFileCheckSum.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Common/Classes/General/InternalKryptonMessageBoxExtended.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Common/Classes/Internal/InternalExtendedKryptonMessageBox.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Core/Controls Visuals/CoreKryptonMessageBoxExtendedForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Core/Controls/Internal/CoreInternalKryptonMessageBoxExtended.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Developer.Utilities/Controls Visuals/KryptonMessageBoxExtended.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.InputBox/Controls Visuals/KryptonInputBoxExtendedForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.InputBox/Controls Visuals/KryptonInputBoxExtendedFormTest.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Memory.Box/UX/KryptonMemoryBox.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Messagebox/Controls Toolkit/InternalKryptonButton.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Messagebox/Controls Visuals/KryptonMessageBoxExtendedForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Navi.Suite/UX/NaviOptionsForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Outlook.Grid/Control Visuals/Formatting/CustomFormatRule.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Settings/Classes/Other/ExtendedKryptonMessageBox.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater/Auto Updater/UX/RemindLaterWindow.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Theme.Switcher/UX/KryptonExternalThemeSelectorForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Toast/Controls Toolkit/KryptonToastButton.cs

* Updated to reflect ST latest changes

* Updated to reflect ST latest changes

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Messagebox/Controls Toolkit/KryptonMessageBoxExtended.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Messagebox/Controls Visuals/KryptonMessageBoxExtendedForm.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Messagebox/Globals/GlobalDeclarations.cs
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater/Sharp Update/Classes/Hasher.cs

* Text alignment in `KryptonMessageBoxExtended`

* Text alignment in `KryptonMessageBoxExtended`

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Forms/Values/FadeValues.cs

[Issue 1584-Move-FadeForm-into-Extended-until-issues-are-sorted](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1584)
Adds FadeValues to: Extended-Toolkit\Source\Krypton Toolkit\Krypton.Toolkit.Suite.Extended.Forms\Values
And the change log

1584 move fade form into extended until issues are sorted

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton Toolkit Suite Extended 2022 - VS2022 - NuGet.slnx

* Implemented #522

---

Documents/Help/Changelog.md
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Core/Krypton.Toolkit.Suite.Extended.Core 2022.csproj
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Data.Visualisation/Krypton.Toolkit.Suite.Extended.Data.Visualisation 2022.csproj
Source/Krypton Toolkit/Krypton.Toolkit.Suite.Extended.Software.Updater.Core/Krypton.Toolkit.Suite.Extended.Software.Updater.Core 2022.csproj
Source/Krypton Toolkit/ZipExtractor/ZipExtractor.csproj

* Fix for #529 - V95
